export const backImgg = require("./backgroundImg.png")
export const lineImg = require("./line.png")
export const facebookLogo = require("./facebook.png")
export const googleLogo = require("./google.png")
export const appleLogo = require("./Apple.png")
export const userIcon = require("./userIcon.png")
export const checked = require("./checked.png")
export const closeEye = require("./Eye.png")
export const openEye = require("./openEye.png")
export const leftArrow = require("./leftArrow.png")
export const reload = require("./reload.png")
export const generCheck = require("./generCheck.png")
export const add = require("./add.png")
export const detailBgImg = require("./detailBg.png")

