export const popBold = "Poppins-Bold"
export const popBoldItalic = "Poppins-BoldItalic"
export const popMediumItalic = "Poppins-MediumItalic"
export const popMedium = "Poppins-Medium"
export const regular ="Poppins-Regular"
export const semiBold = "Poppins-SemiBold"